name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name:  deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Add your Docker Hub username as a secret
          password: ${{ secrets.DOCKER_PASSWORD }}  # Add your Docker Hub password as a secret

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t mintah/fastapi-hng:latest .

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push mintah/fastapi-hng:latest

      # Step 6: SSH into EC2 and run Docker-related tasks
      - name: SSH to EC2 and deploy the application
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_HOST }}  # EC2 IP 
          username: ${{ secrets.REMOTE_USER }}  # SSH username (e.g., ec2-user, ubuntu)
          key: ${{ secrets.REMOTE_SSH_KEY }}  # SSH private key (added as GitHub secret)
          port: 22  # SSH port (default is 22)
          script: |
            # Run commands on the EC2 instance
            echo "Running on EC2 server"
            cd my_hng_app  # Navigate to  app directory
            # Download the docker-compose.yml file from the GitHub repository
            curl -o docker-compose.yml https://raw.githubusercontent.com/lay-ke/fastapi-book-project/main/docker-compose.yml  # Replace with actual URL to your docker-compose.yml
            curl -o docker-compose.yml https://raw.githubusercontent.com/lay-ke/fastapi-book-project/main/nginx.conf
            # Stop and remove existing containers if any
            echo "Stopping and removing old containers (if any)"
            docker-compose down --volumes || echo "No existing containers to remove."

            # Pull the latest images (if needed)
            echo "Pulling latest images"
            docker-compose pull  # This will pull any updated images from the registry

            # Start the services with the new containers
            echo "Starting containers with docker-compose"
            docker-compose up -d  # Starts containers in detached mode
