name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name:  deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Add your Docker Hub username as a secret
          password: ${{ secrets.DOCKER_PASSWORD }}  # Add your Docker Hub password as a secret

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t mintah/fastapi-hng:latest .

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push mintah/fastapi-hng:latest

      # Step 6: SSH into EC2 and run Docker-related tasks
      - name: SSH to EC2 and deploy the application
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_HOST }}  # EC2 IP 
          username: ${{ secrets.REMOTE_USER }}  # SSH username (e.g., ec2-user, ubuntu)
          key: ${{ secrets.REMOTE_SSH_KEY }}  # SSH private key (added as GitHub secret)
          port: 22  # SSH port (default is 22)
          script: |
            # Run commands on the EC2 instance
            echo "Running on EC2 server"
            cd my_hng_app  # Navigate to your app directory
            docker pull mintah/fastapi-hng:latest  # Pull the latest Docker image from Docker Hub
            docker stop myapp-container || true  # Stop any existing container (ignore if not running)
            docker rm myapp-container || true  # Remove the old container (ignore if not running)
            docker run -d --name myapp-container mintah/fastapi-hng:latest  # Start the new container
